services:
    postgres:
        image: postgres:14.2-alpine
        environment:
            - POSTGRES_PASSWORD=supersecurepassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "boolean-data:/var/lib/postgresql/data/pgdata"
    boolean:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        restart: unless-stopped
        depends_on:
            - postgres
volumes:
    boolean-data: {}
