services:
    postgres:
        image: postgres:14.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=supersecurepassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "boolean-data:/var/lib/postgresql/data/pgdata"
    boolean:
        build: .
        environment:
            - DATABASE_URL=postgresql://postgres:supersecurepassword@postgres/postgres?schema=boolean
        env_file:
            - .env
        restart: unless-stopped 
        depends_on:
            - postgres
volumes:
    boolean-data: {}
